// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#ifndef PROTOBUF_request_2eproto__INCLUDED
#define PROTOBUF_request_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace INF {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_request_2eproto();
void protobuf_AssignDesc_request_2eproto();
void protobuf_ShutdownFile_request_2eproto();

class INF_Desc;
class INF_Desc_INF_Base;
class INF_Desc_INF_Feature;

// ===================================================================

class INF_Desc_INF_Base : public ::google::protobuf::Message {
 public:
  INF_Desc_INF_Base();
  virtual ~INF_Desc_INF_Base();

  INF_Desc_INF_Base(const INF_Desc_INF_Base& from);

  inline INF_Desc_INF_Base& operator=(const INF_Desc_INF_Base& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const INF_Desc_INF_Base& default_instance();

  void Swap(INF_Desc_INF_Base* other);

  // implements Message ----------------------------------------------

  inline INF_Desc_INF_Base* New() const { return New(NULL); }

  INF_Desc_INF_Base* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const INF_Desc_INF_Base& from);
  void MergeFrom(const INF_Desc_INF_Base& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(INF_Desc_INF_Base* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 nBaseID = 1;
  void clear_nbaseid();
  static const int kNBaseIDFieldNumber = 1;
  ::google::protobuf::int64 nbaseid() const;
  void set_nbaseid(::google::protobuf::int64 value);

  // optional string strBaseName = 2;
  void clear_strbasename();
  static const int kStrBaseNameFieldNumber = 2;
  const ::std::string& strbasename() const;
  void set_strbasename(const ::std::string& value);
  void set_strbasename(const char* value);
  void set_strbasename(const char* value, size_t size);
  ::std::string* mutable_strbasename();
  ::std::string* release_strbasename();
  void set_allocated_strbasename(::std::string* strbasename);

  // optional int32 nBaseThreashold = 3;
  void clear_nbasethreashold();
  static const int kNBaseThreasholdFieldNumber = 3;
  ::google::protobuf::int32 nbasethreashold() const;
  void set_nbasethreashold(::google::protobuf::int32 value);

  // optional int32 nStatus = 4;
  void clear_nstatus();
  static const int kNStatusFieldNumber = 4;
  ::google::protobuf::int32 nstatus() const;
  void set_nstatus(::google::protobuf::int32 value);

  // optional int32 nLoadMode = 5;
  void clear_nloadmode();
  static const int kNLoadModeFieldNumber = 5;
  ::google::protobuf::int32 nloadmode() const;
  void set_nloadmode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:INF.INF_Desc.INF_Base)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 nbaseid_;
  ::google::protobuf::internal::ArenaStringPtr strbasename_;
  ::google::protobuf::int32 nbasethreashold_;
  ::google::protobuf::int32 nstatus_;
  ::google::protobuf::int32 nloadmode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_request_2eproto();
  friend void protobuf_AssignDesc_request_2eproto();
  friend void protobuf_ShutdownFile_request_2eproto();

  void InitAsDefaultInstance();
  static INF_Desc_INF_Base* default_instance_;
};
// -------------------------------------------------------------------

class INF_Desc_INF_Feature : public ::google::protobuf::Message {
 public:
  INF_Desc_INF_Feature();
  virtual ~INF_Desc_INF_Feature();

  INF_Desc_INF_Feature(const INF_Desc_INF_Feature& from);

  inline INF_Desc_INF_Feature& operator=(const INF_Desc_INF_Feature& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const INF_Desc_INF_Feature& default_instance();

  void Swap(INF_Desc_INF_Feature* other);

  // implements Message ----------------------------------------------

  inline INF_Desc_INF_Feature* New() const { return New(NULL); }

  INF_Desc_INF_Feature* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const INF_Desc_INF_Feature& from);
  void MergeFrom(const INF_Desc_INF_Feature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(INF_Desc_INF_Feature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 nObjectID = 1;
  void clear_nobjectid();
  static const int kNObjectIDFieldNumber = 1;
  ::google::protobuf::int64 nobjectid() const;
  void set_nobjectid(::google::protobuf::int64 value);

  // optional int32 nObjectThreashold = 2;
  void clear_nobjectthreashold();
  static const int kNObjectThreasholdFieldNumber = 2;
  ::google::protobuf::int32 nobjectthreashold() const;
  void set_nobjectthreashold(::google::protobuf::int32 value);

  // optional int64 nFeatureID = 3;
  void clear_nfeatureid();
  static const int kNFeatureIDFieldNumber = 3;
  ::google::protobuf::int64 nfeatureid() const;
  void set_nfeatureid(::google::protobuf::int64 value);

  // optional int32 nFeatureThreashold = 4;
  void clear_nfeaturethreashold();
  static const int kNFeatureThreasholdFieldNumber = 4;
  ::google::protobuf::int32 nfeaturethreashold() const;
  void set_nfeaturethreashold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:INF.INF_Desc.INF_Feature)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 nobjectid_;
  ::google::protobuf::int64 nfeatureid_;
  ::google::protobuf::int32 nobjectthreashold_;
  ::google::protobuf::int32 nfeaturethreashold_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_request_2eproto();
  friend void protobuf_AssignDesc_request_2eproto();
  friend void protobuf_ShutdownFile_request_2eproto();

  void InitAsDefaultInstance();
  static INF_Desc_INF_Feature* default_instance_;
};
// -------------------------------------------------------------------

class INF_Desc : public ::google::protobuf::Message {
 public:
  INF_Desc();
  virtual ~INF_Desc();

  INF_Desc(const INF_Desc& from);

  inline INF_Desc& operator=(const INF_Desc& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const INF_Desc& default_instance();

  void Swap(INF_Desc* other);

  // implements Message ----------------------------------------------

  inline INF_Desc* New() const { return New(NULL); }

  INF_Desc* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const INF_Desc& from);
  void MergeFrom(const INF_Desc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(INF_Desc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef INF_Desc_INF_Base INF_Base;
  typedef INF_Desc_INF_Feature INF_Feature;

  // accessors -------------------------------------------------------

  // optional int32 inputnum = 1;
  void clear_inputnum();
  static const int kInputnumFieldNumber = 1;
  ::google::protobuf::int32 inputnum() const;
  void set_inputnum(::google::protobuf::int32 value);

  // repeated .INF.INF_Desc.INF_Base base = 2;
  int base_size() const;
  void clear_base();
  static const int kBaseFieldNumber = 2;
  const ::INF::INF_Desc_INF_Base& base(int index) const;
  ::INF::INF_Desc_INF_Base* mutable_base(int index);
  ::INF::INF_Desc_INF_Base* add_base();
  ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Base >*
      mutable_base();
  const ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Base >&
      base() const;

  // repeated .INF.INF_Desc.INF_Feature feature = 3;
  int feature_size() const;
  void clear_feature();
  static const int kFeatureFieldNumber = 3;
  const ::INF::INF_Desc_INF_Feature& feature(int index) const;
  ::INF::INF_Desc_INF_Feature* mutable_feature(int index);
  ::INF::INF_Desc_INF_Feature* add_feature();
  ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Feature >*
      mutable_feature();
  const ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Feature >&
      feature() const;

  // @@protoc_insertion_point(class_scope:INF.INF_Desc)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Base > base_;
  ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Feature > feature_;
  ::google::protobuf::int32 inputnum_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_request_2eproto();
  friend void protobuf_AssignDesc_request_2eproto();
  friend void protobuf_ShutdownFile_request_2eproto();

  void InitAsDefaultInstance();
  static INF_Desc* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// INF_Desc_INF_Base

// optional int64 nBaseID = 1;
inline void INF_Desc_INF_Base::clear_nbaseid() {
  nbaseid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 INF_Desc_INF_Base::nbaseid() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Base.nBaseID)
  return nbaseid_;
}
inline void INF_Desc_INF_Base::set_nbaseid(::google::protobuf::int64 value) {
  
  nbaseid_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Base.nBaseID)
}

// optional string strBaseName = 2;
inline void INF_Desc_INF_Base::clear_strbasename() {
  strbasename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& INF_Desc_INF_Base::strbasename() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Base.strBaseName)
  return strbasename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void INF_Desc_INF_Base::set_strbasename(const ::std::string& value) {
  
  strbasename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Base.strBaseName)
}
inline void INF_Desc_INF_Base::set_strbasename(const char* value) {
  
  strbasename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:INF.INF_Desc.INF_Base.strBaseName)
}
inline void INF_Desc_INF_Base::set_strbasename(const char* value, size_t size) {
  
  strbasename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:INF.INF_Desc.INF_Base.strBaseName)
}
inline ::std::string* INF_Desc_INF_Base::mutable_strbasename() {
  
  // @@protoc_insertion_point(field_mutable:INF.INF_Desc.INF_Base.strBaseName)
  return strbasename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* INF_Desc_INF_Base::release_strbasename() {
  // @@protoc_insertion_point(field_release:INF.INF_Desc.INF_Base.strBaseName)
  
  return strbasename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void INF_Desc_INF_Base::set_allocated_strbasename(::std::string* strbasename) {
  if (strbasename != NULL) {
    
  } else {
    
  }
  strbasename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strbasename);
  // @@protoc_insertion_point(field_set_allocated:INF.INF_Desc.INF_Base.strBaseName)
}

// optional int32 nBaseThreashold = 3;
inline void INF_Desc_INF_Base::clear_nbasethreashold() {
  nbasethreashold_ = 0;
}
inline ::google::protobuf::int32 INF_Desc_INF_Base::nbasethreashold() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Base.nBaseThreashold)
  return nbasethreashold_;
}
inline void INF_Desc_INF_Base::set_nbasethreashold(::google::protobuf::int32 value) {
  
  nbasethreashold_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Base.nBaseThreashold)
}

// optional int32 nStatus = 4;
inline void INF_Desc_INF_Base::clear_nstatus() {
  nstatus_ = 0;
}
inline ::google::protobuf::int32 INF_Desc_INF_Base::nstatus() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Base.nStatus)
  return nstatus_;
}
inline void INF_Desc_INF_Base::set_nstatus(::google::protobuf::int32 value) {
  
  nstatus_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Base.nStatus)
}

// optional int32 nLoadMode = 5;
inline void INF_Desc_INF_Base::clear_nloadmode() {
  nloadmode_ = 0;
}
inline ::google::protobuf::int32 INF_Desc_INF_Base::nloadmode() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Base.nLoadMode)
  return nloadmode_;
}
inline void INF_Desc_INF_Base::set_nloadmode(::google::protobuf::int32 value) {
  
  nloadmode_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Base.nLoadMode)
}

// -------------------------------------------------------------------

// INF_Desc_INF_Feature

// optional int64 nObjectID = 1;
inline void INF_Desc_INF_Feature::clear_nobjectid() {
  nobjectid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 INF_Desc_INF_Feature::nobjectid() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Feature.nObjectID)
  return nobjectid_;
}
inline void INF_Desc_INF_Feature::set_nobjectid(::google::protobuf::int64 value) {
  
  nobjectid_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Feature.nObjectID)
}

// optional int32 nObjectThreashold = 2;
inline void INF_Desc_INF_Feature::clear_nobjectthreashold() {
  nobjectthreashold_ = 0;
}
inline ::google::protobuf::int32 INF_Desc_INF_Feature::nobjectthreashold() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Feature.nObjectThreashold)
  return nobjectthreashold_;
}
inline void INF_Desc_INF_Feature::set_nobjectthreashold(::google::protobuf::int32 value) {
  
  nobjectthreashold_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Feature.nObjectThreashold)
}

// optional int64 nFeatureID = 3;
inline void INF_Desc_INF_Feature::clear_nfeatureid() {
  nfeatureid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 INF_Desc_INF_Feature::nfeatureid() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Feature.nFeatureID)
  return nfeatureid_;
}
inline void INF_Desc_INF_Feature::set_nfeatureid(::google::protobuf::int64 value) {
  
  nfeatureid_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Feature.nFeatureID)
}

// optional int32 nFeatureThreashold = 4;
inline void INF_Desc_INF_Feature::clear_nfeaturethreashold() {
  nfeaturethreashold_ = 0;
}
inline ::google::protobuf::int32 INF_Desc_INF_Feature::nfeaturethreashold() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.INF_Feature.nFeatureThreashold)
  return nfeaturethreashold_;
}
inline void INF_Desc_INF_Feature::set_nfeaturethreashold(::google::protobuf::int32 value) {
  
  nfeaturethreashold_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.INF_Feature.nFeatureThreashold)
}

// -------------------------------------------------------------------

// INF_Desc

// optional int32 inputnum = 1;
inline void INF_Desc::clear_inputnum() {
  inputnum_ = 0;
}
inline ::google::protobuf::int32 INF_Desc::inputnum() const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.inputnum)
  return inputnum_;
}
inline void INF_Desc::set_inputnum(::google::protobuf::int32 value) {
  
  inputnum_ = value;
  // @@protoc_insertion_point(field_set:INF.INF_Desc.inputnum)
}

// repeated .INF.INF_Desc.INF_Base base = 2;
inline int INF_Desc::base_size() const {
  return base_.size();
}
inline void INF_Desc::clear_base() {
  base_.Clear();
}
inline const ::INF::INF_Desc_INF_Base& INF_Desc::base(int index) const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.base)
  return base_.Get(index);
}
inline ::INF::INF_Desc_INF_Base* INF_Desc::mutable_base(int index) {
  // @@protoc_insertion_point(field_mutable:INF.INF_Desc.base)
  return base_.Mutable(index);
}
inline ::INF::INF_Desc_INF_Base* INF_Desc::add_base() {
  // @@protoc_insertion_point(field_add:INF.INF_Desc.base)
  return base_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Base >*
INF_Desc::mutable_base() {
  // @@protoc_insertion_point(field_mutable_list:INF.INF_Desc.base)
  return &base_;
}
inline const ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Base >&
INF_Desc::base() const {
  // @@protoc_insertion_point(field_list:INF.INF_Desc.base)
  return base_;
}

// repeated .INF.INF_Desc.INF_Feature feature = 3;
inline int INF_Desc::feature_size() const {
  return feature_.size();
}
inline void INF_Desc::clear_feature() {
  feature_.Clear();
}
inline const ::INF::INF_Desc_INF_Feature& INF_Desc::feature(int index) const {
  // @@protoc_insertion_point(field_get:INF.INF_Desc.feature)
  return feature_.Get(index);
}
inline ::INF::INF_Desc_INF_Feature* INF_Desc::mutable_feature(int index) {
  // @@protoc_insertion_point(field_mutable:INF.INF_Desc.feature)
  return feature_.Mutable(index);
}
inline ::INF::INF_Desc_INF_Feature* INF_Desc::add_feature() {
  // @@protoc_insertion_point(field_add:INF.INF_Desc.feature)
  return feature_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Feature >*
INF_Desc::mutable_feature() {
  // @@protoc_insertion_point(field_mutable_list:INF.INF_Desc.feature)
  return &feature_;
}
inline const ::google::protobuf::RepeatedPtrField< ::INF::INF_Desc_INF_Feature >&
INF_Desc::feature() const {
  // @@protoc_insertion_point(field_list:INF.INF_Desc.feature)
  return feature_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace INF

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_request_2eproto__INCLUDED
